### PR TITLE
Allow configuration by encapsulation of the code in functions or macros

### PR DESCRIPTION
**Pull request by aminya**
This allows configuring various parameters of the includes through function/macro arguments (e.g. target names, paths, etc.).

This is a breaking change as now the function/macros should be called. 

Tip for the review: hide the whitespace changes from the GitHub UI!

### CODE REVIEW

**Comment by aminya** [comment]
@sudara What do yo think about this?

**Comment by aminya** [comment]
This allows configuring various parameters of the includes through function/macro arguments (e.g. target names, paths, etc.). So instead of forcing the asset target to be `Assets` or to have the `SharedCode` target on the users, they can decide if they want what should be their names. Similar for other parameters.

**Comment by sudara** [comment]
I understand the intention here — I also wish the cmake in pamplejuce could be better encapsulated.

However, I think since Pamplejuce is a template repo, reusability is limited in quite a nasty way — each project gets a point in time "copy" of the pamplejuce code. Given that, I think after this PR encapsulates code in functions, we end up with all the same problems, plus additional complexity for people to wade through when they are updating. This wouldn't be the case if they were just consuming this as a library (vs. from a point in time copy of Pamplejuce).

Hopefully that makes sense! Thanks for submitting the contribution! Happy to chat further on discord, etc...

**Comment by aminya** [comment]
@sudara If the concern is backwards compatibility, I can do that. We just need to provide a file that calls these functions when it is included. I highly recommend considering this again. The C++ community needs to be more agile in adopting better practices.

**Comment by aminya** [comment]
Thanks for the explanation. I'll be maintaining these changes in my fork then. It would be great if you link to my repository in the README in case someone needs more control and reusability.

**Pull request closed without merging**
